version: '3.8'
services:
  envoy:
    image: envoyproxy/envoy:v1.29-latest
    ports:
      - "9901:9901" # Admin interface
      - "10000:10000" # Example listener
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - envoy-net
  envoy-gateway:
    image: envoyproxy/gateway-dev:latest
    ports:
      - "8080:8080"
    networks:
      - envoy-net
    depends_on:
      - envoy
  backend1:
    build: ./backend-service
    image: backend-service:latest
    environment:
      - INSTANCE_NAME=backend1
    ports:
      - "8081:8080"
    networks:
      - envoy-net
  backend2:
    image: backend-service:latest
    environment:
      - INSTANCE_NAME=backend2
    ports:
      - "8082:8080"
    networks:
      - envoy-net
networks:
  envoy-net:
    driver: bridge
