services:
  envoy:
    image: envoyproxy/envoy:v1.29-latest
    command: ["envoy", "-c", "/etc/envoy/bootstrap.yaml"]
    ports:
      - "9090:19000" # Admin interface
      - "8080:8080" # Example listener
    volumes:
      - ./config/bootstrap.yaml:/etc/envoy/bootstrap.yaml:ro
      - ./config/dynamic_configs:/etc/envoy/dynamic_configs:ro
    networks:
      - envoy-net
  backend1:
    build: ./backend-service
    image: backend-service:latest
    environment:
      - INSTANCE_NAME=backend1
      - INSTANCE_PORT=8081
    ports:
      - "8081:8081"
    networks:
      - envoy-net
  backend2:
    image: backend-service:latest
    environment:
      - INSTANCE_NAME=backend2
      - INSTANCE_PORT=8082
    ports:
      - "8082:8082"
    networks:
      - envoy-net
networks:
  envoy-net:
    driver: bridge
