services:
  backend1:
    build: .
    image: backend-service:latest
    environment:
      - INSTANCE_NAME=backend1
    ports:
      - "8081:8080"
  backend2:
    image: backend-service:latest
    environment:
      - INSTANCE_NAME=backend2
    ports:
      - "8082:8080"
    depends_on:
      - backend1
